In [1]:
import pandas as pd

In [2]:
df_bureau = pd.read_csv('data/raw/bureau.csv')
df_previous_applications = pd.read_csv('data/raw/previous_application.csv')
df_installments_payments = pd.read_csv('data/raw/installments_payments.csv')

In [3]:
df_description = pd.read_csv('data/raw/HomeCredit_columns_description.csv', encoding='latin1')

In [4]:
df_description['Table'].value_counts()

Table
application_{train|test}.csv    122
previous_application.csv         38
credit_card_balance.csv          23
bureau.csv                       17
POS_CASH_balance.csv              8
installments_payments.csv         8
bureau_balance.csv                3
Name: count, dtype: int64

In [5]:
df_description[df_description['Table'] == 'previous_application.csv'].loc[:, ['Row', 'Description']]

,Row,Description
173,SK_ID_PREV,ID of previous credit in Home credit related t...
174,SK_ID_CURR,ID of loan in our sample
175,NAME_CONTRACT_TYPE,"Contract product type (Cash loan, consumer loa..."
176,AMT_ANNUITY,Annuity of previous application
177,AMT_APPLICATION,For how much credit did client ask on the prev...
178,AMT_CREDIT,Final credit amount on the previous applicatio...
179,AMT_DOWN_PAYMENT,Down payment on the previous application
180,AMT_GOODS_PRICE,Goods price of good that client asked for (if ...
181,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply ...
182,HOUR_APPR_PROCESS_START,Approximately at what day hour did the client ...
183,FLAG_LAST_APPL_PER_CONTRACT,Flag if it was last application for the previo...
184,NFLAG_LAST_APPL_IN_DAY,Flag if the application was the last applicati...
185,NFLAG_MICRO_CASH,Flag Micro finance loan
186,RATE_DOWN_PAYMENT,Down payment rate normalized on previous credit
187,RATE_INTEREST_PRIMARY,Interest rate normalized on previous credit
188,RATE_INTEREST_PRIVILEGED,Interest rate normalized on previous credit
189,NAME_CASH_LOAN_PURPOSE,Purpose of the cash loan
190,NAME_CONTRACT_STATUS,"Contract status (approved, cancelled, ...) of ..."
191,DAYS_DECISION,Relative to current application when was the d...
192,NAME_PAYMENT_TYPE,Payment method that client chose to pay for th...
193,CODE_REJECT_REASON,Why was the previous application rejected
194,NAME_TYPE_SUITE,Who accompanied client when applying for the p...
195,NAME_CLIENT_TYPE,Was the client old or new client when applying...
196,NAME_GOODS_CATEGORY,What kind of goods did the client apply for in...
197,NAME_PORTFOLIO,"Was the previous application for CASH, POS, CA..."
198,NAME_PRODUCT_TYPE,Was the previous application x-sell o walk-in
199,CHANNEL_TYPE,Through which channel we acquired the client o...
200,SELLERPLACE_AREA,Selling area of seller place of the previous a...
201,NAME_SELLER_INDUSTRY,The industry of the seller
202,CNT_PAYMENT,Term of previous credit at application of the ...
203,NAME_YIELD_GROUP,Grouped interest rate into small medium and hi...
204,PRODUCT_COMBINATION,Detailed product combination of the previous a...
205,DAYS_FIRST_DRAWING,Relative to application date of current applic...
206,DAYS_FIRST_DUE,Relative to application date of current applic...
207,DAYS_LAST_DUE_1ST_VERSION,Relative to application date of current applic...
208,DAYS_LAST_DUE,Relative to application date of current applic...
209,DAYS_TERMINATION,Relative to application date of current applic...
210,NFLAG_INSURED_ON_APPROVAL,Did the client requested insurance during the ...

In [6]:
df_previous_applications.head(10)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
5,1383531,199383,Cash loans,23703.930,315000.0,340573.5,NaN,315000.0,SATURDAY,8,...,XNA,18.0,low_normal,Cash X-Sell: low,365243.0,-654.0,-144.0,-144.0,-137.0,1.0
6,2315218,175704,Cash loans,NaN,0.0,0.0,NaN,NaN,TUESDAY,11,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
7,1656711,296299,Cash loans,NaN,0.0,0.0,NaN,NaN,MONDAY,7,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
8,2367563,342292,Cash loans,NaN,0.0,0.0,NaN,NaN,MONDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
9,2579447,334349,Cash loans,NaN,0.0,0.0,NaN,NaN,SATURDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN